ObjetocriadoLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:781229711255:function:bibliotecaserverless-dev-objetocriado:79"
UserPoolClientId = "39c2ajfohe29b7q12s79t08c9"
EndpointPort = "3306"
BucketName = "teste321hhelter"
UserPoolId = "us-east-1_AlJfHtIhM"
EnviarsmsLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:781229711255:function:bibliotecaserverless-dev-enviarsms:79"
ConsultardbLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:781229711255:function:bibliotecaserverless-dev-consultardb:79"
ListarLambdaFunctionQualifiedArn = "arn:aws:lambda:us-east-1:781229711255:function:bibliotecaserverless-dev-listar:79"
UserPoolClientName = "test-user-pool-client-dev"
ServiceEndpoint = "https://2ckhjqhbxg.execute-api.us-east-1.amazonaws.com/dev"
ServerlessDeploymentBucketName = "bibliotecaserverless-dev-serverlessdeploymentbuck-1w6ip0qrphbw7"
EndpointAddress = "bibliotecaserverless.cfvdsldbqezf.us-east-1.rds.amazonaws.com"